spring:
  application:
    name: Fx
  datasource:
    url: jdbc:mysql://localhost:3306/fxAccount
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

#below if uncommented will enable dev profile if we run through normally without terminal mvn command
#  profiles:
#    active: dev
#logging:
#  level:
#    root: info
#    org.hibernate.orm.boot: debug
#debug: true
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
fx:
  message: local-hello
