spring:
  application:
    name: Fx
  datasource:
    url: jdbc:mysql://localhost:3306/fxAccount
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

#below if uncommented will enable dev profile if we run through normally without terminal mvn command
#  profiles:
#    active: dev
logging:
  level:
    root: info
    org.hibernate.orm.boot: debug
#debug: true
fx:
  message: local-hello
